server:
  port: 8079

# Gateway routing
spring:
  cloud:
    gateway:
      routes: # Basic Routing for testing purposes
        - id: user
          uri: http://localhost:8088/
          predicates:
            - Path=/user/**
        - id: course
          uri: http://localhost:8081/
          predicates:
            - Path=/course/**
        - id: institution
          uri: http://localhost:8082/
          predicates:
            - Path=/institution/**
